coverage:
  status:
    project:
      default:
        enabled: yes
        target: auto
    patch:
      default:
        enabled: yes
        target: 100%

comment: false

ignore:
  - 'codejail_service/docker_gunicorn_configuration.py'
